# .github/actions/setup-environment/action.yml
# 환경 설정 복합 액션
name: 'Setup Development Environment'
description: 'Sets up Java, Python (optional), Xcode (optional), Gradle cache, and Gradle.'
inputs:
  java-version:
    description: 'Java 버전'
    required: false
    default: '17'
  java-distribution:
    description: 'Java 배포판'
    required: false
    default: 'temurin'
  setup-python:
    description: 'Python 설정 여부'
    required: false
    default: 'false' # 문자열 'false'로 비교
  python-version:
    description: 'Python 버전'
    required: false
    default: '3.x'
  setup-xcode:
    description: 'Xcode 설정 여부'
    required: false
    default: 'false' # 문자열 'false'로 비교
  xcode-version:
    description: 'Xcode 버전'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    # 1. Java(JDK) 설정
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    # 2. Python 설정 (필요 시)
    - name: Set up Python
      if: inputs.setup-python == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        # Python 캐시 추가 가능 (pip 등 사용 시)
        # cache: 'pip'

    # 3. Xcode 설정 (macOS 빌드 시)
    # 이 액션은 Ubuntu 또는 macOS에서 실행될 수 있음. macOS에서만 Xcode 설정 실행.
    - name: Set up Xcode (if applicable on macOS)
      if: runner.os == 'macOS' && inputs.setup-xcode == 'true'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    # 4. Gradle 캐시 설정
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        # 캐시 키는 OS와 Gradle 관련 파일 해시 기반
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle.kts', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 5. Gradle 설정 (Wrapper 사용 권장)
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
