name: Build Native Binaries

on:
  workflow_call:
    inputs:
      platform:
        description: '빌드할 플랫폼 (android, ios, windows, macos, linux)'
        required: true
        type: string
      gradle-task:
        description: '실행할 Gradle 작업'
        required: true
        type: string
      artifact-name:
        description: '아티팩트 이름'
        required: true
        type: string
      artifact-path:
        description: '아티팩트 경로 패턴'
        required: true
        type: string

jobs:
  build:
    name: Build for ${{ inputs.platform }}
    runs-on: ${{ inputs.platform == 'ios' || inputs.platform == 'macos' && 'macos-latest' || inputs.platform == 'windows' && 'windows-latest' || 'ubuntu-latest' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # macOS/iOS 전용 설정
      - name: Set up Xcode
        if: inputs.platform == 'ios' || inputs.platform == 'macos'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Windows 전용 설정
      - name: Set up MSVC
        if: inputs.platform == 'windows'
        uses: ilammy/msvc-dev-cmd@v1

      # Linux 전용 설정
      - name: Install Linux dependencies
        if: inputs.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ libstdc++-10-dev

      # Gradle 빌드 실행
      - name: Run Gradle task
        run: ./gradlew ${{ inputs.gradle-task }}

      # 빌드 결과물 업로드
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 5
