# .github/actions/publish-library/action.yml
# 라이브러리 퍼블리시 복합 액션 (Gradle 사용)
name: 'Publish Library to Maven Central'
description: 'Sets up GPG and publishes the library using Gradle.'
inputs:
  # Gradle 환경 변수 설정을 위한 입력 (선택적)
  # 직접 secrets를 사용하는 것이 더 일반적일 수 있음
  ossrh-username-env:
    description: 'OSSRH 사용자명 환경 변수 이름'
    required: false
    default: 'OSSRH_USERNAME' # 시크릿 이름과 동일하게
  ossrh-password-env:
    description: 'OSSRH 비밀번호 환경 변수 이름'
    required: false
    default: 'OSSRH_PASSWORD'
  gpg-key-env:
    description: 'GPG 개인 키 환경 변수 이름'
    required: false
    default: 'GPG_PRIVATE_KEY'
  gpg-passphrase-env:
    description: 'GPG 비밀번호 환경 변수 이름'
    required: false
    default: 'GPG_PASSPHRASE'

# 복합 액션은 secrets 컨텍스트 직접 접근 불가. env 통해 전달 필요.
# 호출 워크플로우에서 env로 시크릿을 설정해주어야 함.

runs:
  using: "composite"
  steps:
    # 1. GPG 키 설정
    - name: Setup GPG Key
      shell: bash
      run: |
        # 환경 변수에서 GPG 키 데이터 가져오기
        gpg_private_key_data="${{ env[inputs.gpg-key-env] }}"
        if [[ -z "$gpg_private_key_data" ]]; then
          echo "::error::GPG Private Key secret is not set or empty in environment variable ${{ inputs.gpg-key-env }}."
          exit 1
        fi
        echo "$gpg_private_key_data" | base64 --decode | gpg --batch --import
      # 환경 변수는 호출하는 워크플로우의 env 블록에서 설정되어야 함
      # 예:
      # env:
      #   GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      #   GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      #   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

    # 2. Gradle publish 태스크 실행
    - name: Publish to Maven Central
      shell: bash
      run: ./gradlew publish --build-cache
      env:
        # Gradle이 읽을 환경 변수 설정 (Maven Publish 플러그인 설정과 일치해야 함)
        # 호출 워크플로우에서 설정된 env 변수를 그대로 사용
        ORG_GRADLE_PROJECT_signingKey: ${{ env[inputs.gpg-key-env] }} # 키 자체 전달 필요 시
        ORG_GRADLE_PROJECT_signingPassword: ${{ env[inputs.gpg-passphrase-env] }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ env[inputs.ossrh-username-env] }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ env[inputs.ossrh-password-env] }}
