# .github/actions/prepare-release/action.yml
# 릴리스 준비 복합 액션 (아티팩트 다운로드, 에셋 준비, 정보 생성)
name: 'Prepare Release Assets and Info'
description: 'Downloads build artifacts, prepares release assets, generates release body and zip archive.'
inputs:
  version:
    description: '릴리스 버전 번호 (e.g., 1.0.0)'
    required: true
  python-version:
    description: '사용할 Python 버전'
    required: false
    default: '3.10'
  artifact-download-path:
    description: '빌드 아티팩트를 다운로드할 경로'
    required: false
    default: 'downloaded-artifacts'
  prepared-assets-path:
    description: '준비된 릴리스 에셋을 저장할 경로'
    required: false
    default: 'release-assets'
  output-body-file:
    description: '생성될 릴리스 본문 파일 경로'
    required: false
    default: 'release-body.md'
  output-zip-file-pattern:
    description: '생성될 Zip 파일 이름 패턴 (버전 포함, 예: platform-binaries-{version}.zip)'
    required: false
    default: 'platform-binaries-{version}.zip'

outputs:
  body_path:
    description: '생성된 릴리스 본문 파일의 절대 경로'
    value: ${{ steps.generate_info.outputs.body_path }}
  zip_path:
    description: '생성된 Zip 아카이브 파일의 절대 경로'
    value: ${{ steps.generate_info.outputs.zip_path }}

runs:
  using: "composite"
  steps:
    # 1. Python 설정 (스크립트 실행 위해 필요)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # 2. 모든 빌드 아티팩트 다운로드
    # 기본적으로 모든 아티팩트를 다운로드함
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.artifact-download-path }}

    # 3. 릴리스 에셋 준비 (Python 스크립트 실행)
    # 스크립트는 현재 저장소의 .github/scripts/ 경로에 있어야 함
    - name: Prepare Release Assets
      id: prepare_assets
      # shell: 'bash' 또는 'python' 지정 가능. 기본값은 bash/sh.
      shell: bash
      run: |
        python ${{ github.action_path }}/../../scripts/prepare_release_assets.py \
          --input-dir ${{ inputs.artifact-download-path }} \
          --output-dir ${{ inputs.prepared-assets-path }} \
          --prop-file gradle.properties # 스크립트가 현재 디렉토리의 gradle.properties 참조

    # 4. 릴리스 정보 생성 (본문, Zip) (Python 스크립트 실행)
    - name: Generate Release Info (Body and Zip)
      id: generate_info
      shell: bash
      run: |
        output_zip_file=$(echo "${{ inputs.output-zip-file-pattern }}" | sed "s/{version}/${{ inputs.version }}/g")
        echo "Output zip file name: $output_zip_file"
        python ${{ github.action_path }}/../../scripts/generate_release_info.py \
          --version "${{ inputs.version }}" \
          --assets-dir "${{ inputs.prepared-assets-path }}" \
          --output-body-file "${{ inputs.output-body-file }}" \
          --output-zip-file "$output_zip_file"
      # 스크립트가 GITHUB_OUTPUT을 사용하여 body_path, zip_path 설정
